version: '3.8'

services:
  api:
    build: .
    container_name: e_store_api
    restart: always
    command: ["sh", "-c", "python -m debugpy --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000"]
    volumes:
      - ./e_store_api:/usr/src/app/
    ports:
      - 8000:8000
      - 5678:5678

    env_file:
      - ./.env.dev
  db:
    image: postgres:17
    container_name: e_store_db
    volumes:
      - e_store_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=e_store_db_dev
      - POSTGRES_PASSWORD=e_store_db_dev
      - POSTGRES_DB=e_store_db_dev
  pgadmin:
    image: dpage/pgadmin4
    container_name: e_store_pgadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: test@e-store.com
      PGADMIN_DEFAULT_PASSWORD: abc123
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  e_store_data:
  pgadmin-data:
